In [7]:
# settings.py
from dotenv import load_dotenv
load_dotenv()

# OR, the same with increased verbosity
load_dotenv(verbose=True)

# OR, explicitly providing path to '.env'
from pathlib import Path  # Python 3.6+ only
env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)

True

In [8]:
import tweepy
import webbrowser
import time
import pandas as pd

In [9]:
import os
import mysql.connector
from mysql.connector import Error

try:
    connection = mysql.connector.connect(host = os.getenv('aws_host'),
                                         database = os.getenv('aws_schema'),
                                         user = os.getenv('aws_user'),
                                         password = os.getenv('aws_pass'))
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor = connection.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)

except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if (connection.is_connected()):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

Connected to MySQL Server version  8.0.20
You're connected to database:  ('DORIS_DB',)
MySQL connection is closed

In [10]:
consumer_key = os.getenv("consumer_key")
consumer_secret = os.getenv("consumer_secret")
callback_uri = 'oob'
auth = tweepy.OAuthHandler(consumer_key, consumer_secret, callback_uri)
api = tweepy.API(auth)

In [38]:
def extract_timeline_as_df(timeline_list):
    tweets_data = []
    header_cols = ["id_str", "author", "text", "in_reply_to_user_id", "in_reply_to_status_id", "quoted_status_id", "retweet_count", "favorite_count", "created_at"]

    for status in timeline_list:
        status_dict = dict(vars(status))
        keys = status_dict.keys()
        single_tweet_data = {}
        for k in keys:
            if k == "author":
                single_tweet_data[k] = status.author.screen_name
            else:
                single_tweet_data[k] = status_dict[k]
            
        tweets_data.append(single_tweet_data)
    df = pd.DataFrame(tweets_data, columns=header_cols)
    return df

In [39]:
user = api.get_user("realDonaldTrump")
user_timeline = user.timeline()
df3 = extract_timeline_as_df(user_timeline)
df3

,author,id_str,created_at,text,in_reply_to_user_id,in_reply_to_status_id,quoted_status_id,retweet_count,favorite_count,entities
0,realDonaldTrump,1309696059204141056,2020-09-26 03:27:28,https://t.co/BYFcvME3nv,None,None,NaN,2192,9825,"{'hashtags': [], 'symbols': [], 'user_mentions..."
1,realDonaldTrump,1309681325591281664,2020-09-26 02:28:55,THANK YOU VIRGINIA! #MAGA \nhttps://t.co/py3lL...,None,None,NaN,7633,31032,"{'hashtags': [{'text': 'MAGA', 'indices': [20,..."
2,realDonaldTrump,1309657440753864704,2020-09-26 00:54:00,The Obama Administration was not out to get th...,None,None,NaN,21820,80801,"{'hashtags': [], 'symbols': [], 'user_mentions..."
3,realDonaldTrump,1309642604666126337,2020-09-25 23:55:03,"RT @DanScavino: Florida this morning, Georgia ...",None,None,NaN,7791,0,"{'hashtags': [], 'symbols': [], 'user_mentions..."
4,realDonaldTrump,1309624557897240576,2020-09-25 22:43:20,https://t.co/DFvnZjg2Eh,None,None,NaN,10205,25249,"{'hashtags': [], 'symbols': [], 'user_mentions..."
5,realDonaldTrump,1309619971098632199,2020-09-25 22:25:07,I will NEVER let you down! https://t.co/bqh7UA...,None,None,NaN,13900,45653,"{'hashtags': [], 'symbols': [], 'user_mentions..."
6,realDonaldTrump,1309617799850004480,2020-09-25 22:16:29,A three year HOAX. A failed COUP! https://t.co...,None,None,1.309455e+18,16041,47260,"{'hashtags': [], 'symbols': [], 'user_mentions..."
7,realDonaldTrump,1309617433976672256,2020-09-25 22:15:02,RT @BrookeSingman: NEW: FBI agent William J. B...,None,None,NaN,4214,0,"{'hashtags': [], 'symbols': [], 'user_mentions..."
8,realDonaldTrump,1309617299335385088,2020-09-25 22:14:30,RT @joshgerstein: Just before midnight last ni...,None,None,NaN,5047,0,"{'hashtags': [], 'symbols': [], 'user_mentions..."
9,realDonaldTrump,1309617040068620295,2020-09-25 22:13:28,A great Scam against our Country! https://t.co...,None,None,1.309525e+18,9662,30136,"{'hashtags': [], 'symbols': [], 'user_mentions..."
10,realDonaldTrump,1309616463125385216,2020-09-25 22:11:10,Great! https://t.co/9JOr7kDDG7,None,None,1.309567e+18,11206,76412,"{'hashtags': [], 'symbols': [], 'user_mentions..."
11,realDonaldTrump,1309613172513320966,2020-09-25 21:58:06,Governor Andrew Cuomo of New York wants to put...,None,None,NaN,23154,83108,"{'hashtags': [], 'symbols': [], 'user_mentions..."
12,realDonaldTrump,1309605651769778176,2020-09-25 21:28:13,BIG NEWS! The @Smithsonian American History Mu...,None,None,NaN,13140,58706,"{'hashtags': [], 'symbols': [], 'user_mentions..."
13,realDonaldTrump,1309594346912587777,2020-09-25 20:43:18,https://t.co/ZHqjSQ58NX,None,None,NaN,7151,24514,"{'hashtags': [], 'symbols': [], 'user_mentions..."
14,realDonaldTrump,1309594079823425537,2020-09-25 20:42:14,https://t.co/BP4XACWJXj,None,None,NaN,6069,21442,"{'hashtags': [], 'symbols': [], 'user_mentions..."
15,realDonaldTrump,1309589621630799873,2020-09-25 20:24:31,I was honored to be back in Georgia with a tru...,None,None,NaN,13779,49740,"{'hashtags': [], 'symbols': [], 'user_mentions..."
16,realDonaldTrump,1309561189265965058,2020-09-25 18:31:32,"Just landed in Atlanta, Georgia. On my way now...",None,None,1.309548e+18,9151,40287,"{'hashtags': [], 'symbols': [], 'user_mentions..."
17,realDonaldTrump,1309539128766128129,2020-09-25 17:03:53,Just had a great #LatinosForTrump Roundtable i...,None,None,NaN,15480,55739,"{'hashtags': [{'text': 'LatinosForTrump', 'ind..."
18,realDonaldTrump,1309496170285334529,2020-09-25 14:13:10,RT @thebradfordfile: No journalist has ever as...,None,None,NaN,14875,0,"{'hashtags': [], 'symbols': [], 'user_mentions..."
19,realDonaldTrump,1309496129508302850,2020-09-25 14:13:01,RT @jsolomonReports: Breaking: Flynn case bomb...,None,None,NaN,22821,0,"{'hashtags': [], 'symbols': [], 'user_mentions..."

In [55]:
df3.entities

0     {'hashtags': [], 'symbols': [], 'user_mentions...
1     {'hashtags': [{'text': 'MAGA', 'indices': [20,...
2     {'hashtags': [], 'symbols': [], 'user_mentions...
3     {'hashtags': [], 'symbols': [], 'user_mentions...
4     {'hashtags': [], 'symbols': [], 'user_mentions...
5     {'hashtags': [], 'symbols': [], 'user_mentions...
6     {'hashtags': [], 'symbols': [], 'user_mentions...
7     {'hashtags': [], 'symbols': [], 'user_mentions...
8     {'hashtags': [], 'symbols': [], 'user_mentions...
9     {'hashtags': [], 'symbols': [], 'user_mentions...
10    {'hashtags': [], 'symbols': [], 'user_mentions...
11    {'hashtags': [], 'symbols': [], 'user_mentions...
12    {'hashtags': [], 'symbols': [], 'user_mentions...
13    {'hashtags': [], 'symbols': [], 'user_mentions...
14    {'hashtags': [], 'symbols': [], 'user_mentions...
15    {'hashtags': [], 'symbols': [], 'user_mentions...
16    {'hashtags': [], 'symbols': [], 'user_mentions...
17    {'hashtags': [{'text': 'LatinosForTrump', 'ind...
18    {'hashtags': [], 'symbols': [], 'user_mentions...
19    {'hashtags': [], 'symbols': [], 'user_mentions...
Name: entities, dtype: object

In [65]:
def extract_userdata_as_df(userdata_list):
    users_data = []
    header_cols = ["id_str", "screen_name", "verified", "realName", "url", "followers_count", "friends_count", "created_at"]

    user_dict = dict(vars(user))
    keys = user_dict.keys()
    single_user_data = {}
    for k in keys:
            single_user_data[k] = user_dict[k]

    users_data.append(single_user_data)
    df = pd.DataFrame(users_data, columns=header_cols)
    return df

In [84]:
user = api.get_user("mike_pence")
df4 = extract_userdata_as_df(user)
df4 = df4.where(pd.notnull(df4), None)

In [85]:
def insert_into_table(mySql_insert_query):    
    try:
        connection = mysql.connector.connect(host = os.getenv('aws_host'),
                                             database = os.getenv('aws_schema'),
                                             user = os.getenv('aws_user'),
                                             password = os.getenv('aws_pass'))
        if connection.is_connected():
            db_Info = connection.get_server_info()
            print("Connected to MySQL Server version ", db_Info)

            cursor = connection.cursor()
            for i,row in df4.iterrows():
                cursor.execute(mySql_insert_query, tuple(row))
                connection.commit()
            print(cursor.rowcount, "Success")

    except Error as e:
        print("Error while connecting to MySQL", e)
    finally:
        if (connection.is_connected()):
            cursor.close()
            connection.close()
            print("MySQL connection is closed")

In [86]:
mySql_insert_query = """INSERT INTO USER (userID, screenName, verified, realName, userUrl, followerCount, statusCount, createdAt)
                                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s) """

insert_into_table(mySql_insert_query)

Connected to MySQL Server version  8.0.20
1 Success
MySQL connection is closed